### PR TITLE
添加支付功能

### PR DESCRIPTION
**Pull request by naivehhr**
我这边给添加了支付功能，你看看代码如果OK的可以考虑更新到组件中😃
# 发起支付请求

import WeChatIOS from 'react-native-wechat-ios’;
pay(){
  let payOptions = {
      appId: '',
      nonceStr: '',
      packageValue: '',
      partnerId: '',
      prepayId: '',
      timeStamp: '',
      sign: '',
    };
fetch(url).then(function(res) {
      if (res.ok) {
        res.json().then(function(_data) {
          payOptions['appId'] = _data.appid
          payOptions['nonceStr'] = _data.noncestr
          payOptions['partnerId'] = _data.partnerid
          payOptions['prepayId'] = _data.prepayid
          payOptions['packageValue'] = _data.packageValue
          payOptions['timeStamp'] = _data.timestamp
          payOptions['sign'] = _data.sign
          // console.log("发起支付请求，参数:");
          // console.log(payOptions);
          WeChatIOS.weChatPay(payOptions,(res) => {
              // console.log(res);
           if(res) {
              //console.log
           } else {
              //console.log("请求支付错误,请稍后重试!")
            }
            })

```
    });
```

}
# 

https://facebook.github.io/react-native/docs/native-modules-ios.html#con
tent
componentWillMount(){
subscription = NativeAppEventEmitter.addListener(
        'finishedPay',
        (res) => {
          //console.log('回调的支付结果');
          // console.log(res.length)
          // console.log(res.errCode);
          if(res.errCode == 0) {
            Toast.show('充值成功' + '',Toast.SHORT);
          } else if(res.errCode == -1) {
            Toast.show('支付失败,请稍后尝试' + '',Toast.SHORT);
            this._rechargeFail()
          } else if(res.errCode == -2) {
            console.log("充值取消");
            Toast.show('支付取消' + '',Toast.SHORT);
            this._rechargeFail()
          }
        }
      );
}

componentWillUnmount() {
    if (Platform.OS == 'ios') {
      if(subscription != undefined) {
        // console.log("卸载subscription");
        subscription.remove();
      }
    }
  }

### CODE REVIEW

**Comment by xiaoyann** [comment]
好的，谢谢，我看看

**Comment by xiaoyann** [comment]
合了，有空可以补充下文档哦😄

**Comment by naivehhr** [comment]
代码已测试，文档已补充 :）

**Comment by shexiaoheng** [comment]
@naivehhr 👍

**Pull request merged**
